[package]
name = "wxml_swc_convertor"
version = "0.1.0"
edition = "2018"

[dependencies]
swc_common = { version = "0.11.1", features = ["sourcemap"] }
swc_atoms = "0.2.6"
string_cache = "0.8.1"
swc_ecmascript = {version = "0.53.0",features = ["codegen", "parser",   "visit"]}